// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZPR9yhY14vbTOrcJoEQ38Yexx_9fDK0o',
    appId: '1:796480378787:web:0ae8e42f463aac7c3f2c16',
    messagingSenderId: '796480378787',
    projectId: 'spotify-786',
    authDomain: 'spotify-786.firebaseapp.com',
    storageBucket: 'spotify-786.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCGeKhNUxbhTZjqT02zKKocSlOQ3jEHm4',
    appId: '1:796480378787:android:02dcacab232eeb913f2c16',
    messagingSenderId: '796480378787',
    projectId: 'spotify-786',
    storageBucket: 'spotify-786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP4Pa4RsEtrwkNd7K_kNIiS_KNSuKIhr8',
    appId: '1:796480378787:ios:da2ea0f08f1344933f2c16',
    messagingSenderId: '796480378787',
    projectId: 'spotify-786',
    storageBucket: 'spotify-786.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP4Pa4RsEtrwkNd7K_kNIiS_KNSuKIhr8',
    appId: '1:796480378787:ios:da2ea0f08f1344933f2c16',
    messagingSenderId: '796480378787',
    projectId: 'spotify-786',
    storageBucket: 'spotify-786.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZPR9yhY14vbTOrcJoEQ38Yexx_9fDK0o',
    appId: '1:796480378787:web:6858e0f78ca585443f2c16',
    messagingSenderId: '796480378787',
    projectId: 'spotify-786',
    authDomain: 'spotify-786.firebaseapp.com',
    storageBucket: 'spotify-786.firebasestorage.app',
  );
}
